services:
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
